### ISSUE TITLE
Input matrix is not invertible.

### ISSUE THREAD

**Issue by modianor** [anands-repo/HMM_MNIST#1]
2020-04-30 01:09:52.926388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GT 750M major: 3 minor: 0 memoryClockRate(GHz): 1.085
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.92GiB
2020-04-30 01:09:52.926388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1461] Ignoring visible gpu device (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0, compute capability: 3.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.7.
2020-04-30 01:09:52.927388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-30 01:09:52.927388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2020-04-30 01:09:52.927388: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
	Accuracy for batch 0 = 0.08
	Accuracy for batch 1 = 0.18
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1292, in _do_call
    return fn(*args)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1277, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1367, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible.
	 [[{{node gradients/MultivariateNormalFullCovariance_18/init/Cholesky_grad/MatrixTriangularSolve}} = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MultivariateNormalFullCovariance_18/init/Cholesky, gradients/MultivariateNormalFullCovariance_46/init/Cholesky_grad/eye/MatrixDiag)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pycharm_workspace/HMM_MNIST/run_script.py", line 80, in <module>
    num_epochs=num_epochs, init_file=init_file, saver_prefix=saver_prefix)
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 440, in run_batch
    _, acc = sess.run(fetches=[train_step, accuracy], feed_dict=feed_dict)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 887, in run
    run_metadata_ptr)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1286, in _do_run
    run_metadata)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\client\session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input matrix is not invertible.
	 [[{{node gradients/MultivariateNormalFullCovariance_18/init/Cholesky_grad/MatrixTriangularSolve}} = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MultivariateNormalFullCovariance_18/init/Cholesky, gradients/MultivariateNormalFullCovariance_46/init/Cholesky_grad/eye/MatrixDiag)]]

Caused by op 'gradients/MultivariateNormalFullCovariance_18/init/Cholesky_grad/MatrixTriangularSolve', defined at:
  File "D:/pycharm_workspace/HMM_MNIST/run_script.py", line 80, in <module>
    num_epochs=num_epochs, init_file=init_file, saver_prefix=saver_prefix)
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 403, in run_batch
    train_step = tf.train.AdamOptimizer(learning_rate=self.learning_rate).minimize(cross_entropy)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\training\optimizer.py", line 401, in minimize
    grad_loss=grad_loss)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\training\optimizer.py", line 517, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 596, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 776, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 398, in _MaybeCompile
    return grad_fn()  # Exit early
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gradients_impl.py", line 776, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\linalg_grad.py", line 81, in _CholeskyGrad
    dtype=l.dtype))
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gen_linalg_ops.py", line 1510, in matrix_triangular_solve
    adjoint=adjoint, name=name)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'MultivariateNormalFullCovariance_18/init/Cholesky', defined at:
  File "D:/pycharm_workspace/HMM_MNIST/run_script.py", line 76, in <module>
    Net = HMM.HMM_NN(num_dims=28, num_states=num_states, num_hmms=num_hmms)
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 245, in __init__
    self.HMMs.append(HMM(num_dims=num_dims, num_states=num_states))
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 89, in __init__
    self.states = [State(num_dims) for i in range(num_states)]
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 89, in <listcomp>
    self.states = [State(num_dims) for i in range(num_states)]
  File "D:\pycharm_workspace\HMM_MNIST\HMM.py", line 69, in __init__
    self.dist = tfd.MultivariateNormalFullCovariance(self.mu, self.cov)
  File "D:\Program Files\Python\lib\site-packages\tensorflow_probability\python\distributions\mvn_full_covariance.py", line 177, in __init__
    scale_tril = tf.cholesky(covariance_matrix)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\ops\gen_linalg_ops.py", line 721, in cholesky
    "Cholesky", input=input, name=name)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 3272, in create_op
    op_def=op_def)
  File "D:\Program Files\Python\lib\site-packages\tensorflow\python\framework\ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Input matrix is not invertible.
	 [[{{node gradients/MultivariateNormalFullCovariance_18/init/Cholesky_grad/MatrixTriangularSolve}} = MatrixTriangularSolve[T=DT_DOUBLE, adjoint=false, lower=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MultivariateNormalFullCovariance_18/init/Cholesky, gradients/MultivariateNormalFullCovariance_46/init/Cholesky_grad/eye/MatrixDiag)]]

System environment:

Python3.6
tensorflow-gpu 1.10.0
tensorflow-probability 0.3.0

**Comment by anands-repo** [comment]
Thanks for checking out the codebase.

First of all, I need to mention that the code was written many years ago for a very old version of tensorflow. I cannot guarantee that this is the latest version of the code, or that it will work with a newer version of tensorflow as you are using. So please use the code primarily for reference purposes, rather than to run it directly.

That said, I think this is due to the covariance matrix being non-invertible. You can probably use a quick fix as follows:
```self.sig = tf.Variable(sigma, dtype=tf.float64) + SMALL_VALUE;```

where you define SMALL_VALUE to be a tf.constant value which is some fraction such as 1e-2 or 1e-3 or so. However, I do not remember needing to do that when I ran the code myself.

Also, re-running the code may already fix it without any code changes. This is because the parameters may be reinitialized to different values where this problem doesn't arise.

**Comment by modianor** [comment]
got it! thanks



---Original---
